"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _header_search_results from './header-search-results.bones.json'
import _home_featured_carousel from './home-featured-carousel.bones.json'
import _home_categories from './home-categories.bones.json'
import _home_product_grid from './home-product-grid.bones.json'
import _product_grid from './product-grid.bones.json'
import _product_detail from './product-detail.bones.json'

configureBoneyard({"color":"#e4e4e7","animate":"shimmer","shimmerColor":"#f4f4f5","speed":"1.4s","transition":180})

registerBones({
  "header-search-results": _header_search_results,
  "home-featured-carousel": _home_featured_carousel,
  "home-categories": _home_categories,
  "home-product-grid": _home_product_grid,
  "product-grid": _product_grid,
  "product-detail": _product_detail,
})
