# Generated by Django 6.0.3 on 2026-06-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceenquiry',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
